"""Add fecha_inicio to suscripciones

Revision ID: 8a234fbae6b5
Revises: 
Create Date: 2024-12-22 17:05:44.146554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a234fbae6b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suscripciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_inicio', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suscripciones', schema=None) as batch_op:
        batch_op.drop_column('fecha_inicio')

    # ### end Alembic commands ###
